#! /bin/bash

show_question() {
  echo -e "\033[1;34m$@\033[0m"
}

show_dir() {
  echo -e "\033[1;32m$@\033[0m"
}

show_error() {
  echo -e "\033[1;31m$@\033[0m"
}

end() {
  echo -e "\nExiting...\n"
  exit 0
}

continue() {
  show_question "\nDo you want to continue? (y)es, (n)o : \n"
  read INPUT
  case $INPUT in
    [Yy]* ) ;;
    [Nn]* ) end;;
    * ) show_error "\nSorry, try again."; continue;;
  esac
}

replace() {
  show_question "\nFound an existing installation. Replace it? (y)es, (n)o :\n" 
  read INPUT
  case $INPUT in
    [Yy]* ) rm -rf $DEST_DIR/Eon*;;
    [Nn]* ) ;;
    * ) show_error "\nSorry, try again."; replace $@;;
  esac
}

setup() {
  show_question "\nDo you want to set the theme now? (y)es, (n)o : \n"
  read INPUT
  case $INPUT in
    [Yy]* ) themes;;
    [Nn]* ) end;;
    * ) show_error "\nSorry, try again."; setup;;
  esac
}

themes() {
  show_question "\n+------------------------------------------------------------------+

      Select a number to set the theme you want:

              (a)  EonDark
              (b)  EonDark-Doder
              (c)  EonLight
              (D)  EonLight-Doder


+------------------------------------------------------------------+\n"
  read INPUT
  case $INPUT in
    [Aa]* )  EonDark;;
    [Bb]* )  EonDark-Doder;;
    [Cc]* )  EonLight;;
    [Dd]* )  EonLight-Doder;;
    * ) show_error "\nSorry, try again."; themes;;
  esac
}

EonDark() {

# Set EonDark Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme EonDark
  gsettings set org.gnome.desktop.wm.preferences theme EonDark
  echo "Done!"

}

EonDark-Doder() {

# Set EonDark-Doder Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme EonDark-Doder
  gsettings set org.gnome.desktop.wm.preferences theme EonDark-Doder
  echo "Done!"

}


EonLight() {

# Set EonLight Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme EonLight
  gsettings set org.gnome.desktop.wm.preferences theme EonLight
  echo "Done!"

}

EonLight-Doder() {

# Set EonLight-Doder Gtk Themes
  echo "Setting the theme..."
  gsettings set org.gnome.desktop.interface gtk-theme EonLight-Doder
  gsettings set org.gnome.desktop.wm.preferences theme EonLight-Doder
  echo "Done!"

}



install() {

  # PREVIEW

  # Show destination directory
  echo -e "\nEon Gtk Theme will be installed in:\n"
  show_dir "\t$DEST_DIR"
  if [ "$UID" -eq "$ROOT_UID" ]; then
    echo -e "\nIt will be available to all users."
  else
    echo -e "\nIf you want to make them available to all users, run this script as root."
  fi

  continue

  # INSTALL

  # Check destination directory
  if [ ! -d $DEST_DIR ]; then
    mkdir -p $DEST_DIR
  elif [[ -d $DEST_DIR/EonDark && -d $DEST_DIR/EonDark-Doder && -d $DEST_DIR/EonLight && -d $DEST_DIR/EonLight-Doder ]]; then
    replace $DEST_DIR
  fi

  echo -e "\nInstalling Eon..."
  
  # Copying files

  #./Install
  ./remove-colorful-titlebuttons

  echo -e "\nInstallation complete!"

  setup

}

remove() {

  # PREVIEW

  # Show installation directory
  if [[ -d $DEST_DIR/EonDark && -d $DEST_DIR/EonDark-Doder &&  -d $DEST_DIR/EonLight && -d $DEST_DIR/EonLight-Doder ]]; then
    echo -e "\nEon Gtk Themes installed in:\n"
    show_dir "\t$DEST_DIR"
    if [ "$UID" -eq "$ROOT_UID" ]; then
      echo -e "\nIt will remove for all users."
    else
      echo -e "\nIt will remove only for current user."
    fi

    continue
  
  else
    show_error "\nEon Gtk Themes is not installed in:\n"
    show_dir "\t$DEST_DIR\n"
    end
  fi

  # REMOVE

  echo -e "\nRemoving Eon ..."

  # Removing files

  rm -rf $DEST_DIR/Eon*

  echo "Removing complete!"
  echo "I hope to see you soon."
}

main() {
  show_question "What you want to do: (i)nstall, (r)emove : \n"
  read INPUT
  case $INPUT in
    [Ii]* ) install;;
    [Rr]* ) remove;;
    * ) show_error "\nSorry, try again."; main;;
  esac
}

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.local/share/themes"
fi

echo -e "\e[1m\n+----------------------------------------------+"
echo -e "|      Eon Gtk Themes Installer Script       |"
echo -e "+----------------------------------------------+\n\e[0m"

main
