#!/bin/bash
  # Copying files

ROOT_UID=0
DEST_DIR=

# Destination directory
if [ "$UID" -eq "$ROOT_UID" ]; then
  DEST_DIR="/usr/share/themes"
else
  DEST_DIR="$HOME/.local/share/themes"
fi

repodir=$(cd $(dirname $0) && pwd)
srcdir=${repodir}/src

 rm -rf $DEST_DIR/Eon*

 echo

for variant in 'Dark' 'Light' ; do
  for size in '' ; do
	for color in '' '-Doder'; do
		echo -e "   Installing Eon${variant}${size}${color} ..."

		themedir=$DEST_DIR/Eon${variant}${size}${color}
		install -d ${themedir}

		# Install index.theme
		cd ${srcdir}
		cp -ur \
			index-${variant}${size}${color}.theme \
			${themedir}/index.theme

		# Install GTK+ 2 Theme
		install -d ${themedir}/gtk-2.0
		cd ${srcdir}/gtk-2.0

		cp -ur \
			Eon${color}/assets \
			Eon${color}/apps.rc \
			${themedir}/gtk-2.0

		cp -ur \
			Eon${color}/main${variant}.rc \
			${themedir}/gtk-2.0/main.rc

		cp -ur \
			Eon${color}/gtk${variant}rc \
			${themedir}/gtk-2.0/gtkrc

		# Install GTK+ 3 Theme
		install -d ${themedir}/gtk-3.0
		cd ${srcdir}/gtk-3.0
		cp -ur \
			windows-assets/windows-assets \
			${themedir}/gtk-3.0/
		cp -ur \
			assets${color}/assets \
			${themedir}/gtk-3.0/
		cp -ur \
			scalable \
			${themedir}/gtk-3.0/assets/
		cp -ur \
			gtk${variant}${size}${color}.css \
			${themedir}/gtk-3.0/gtk.css
		cp -ur \
			gtk${size}${color}-dark.css \
			${themedir}/gtk-3.0/gtk-dark.css

		# Install Metacity Theme
		install -d ${themedir}/metacity-1
		cd ${srcdir}/metacity-1/Eon${variant}
		cp -ur \
			*.svg \
			${themedir}/metacity-1

		cp -ur \
			metacity-theme${color}-2.xml \
			${themedir}/metacity-1/metacity-theme-2.xml
		cp -ur \
			metacity-theme${color}-3.xml \
			${themedir}/metacity-1/metacity-theme-3.xml

	done
  done
done

